
-- BELIEVER CONNECT - Supabase database foundation
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  phone text,
  country text,
  church_ministry text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.prayer_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  prayer_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.prayer_requests enable row level security;

create policy "Public profiles are viewable"
on public.profiles for select
to authenticated
using (true);

create policy "Users can create their profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update their profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Authenticated users can view posts"
on public.posts for select
to authenticated
using (true);

create policy "Users can create their own posts"
on public.posts for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can edit their own posts"
on public.posts for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own posts"
on public.posts for delete
to authenticated
using (auth.uid() = user_id);

create policy "Authenticated users can view likes"
on public.post_likes for select
to authenticated
using (true);

create policy "Users can like as themselves"
on public.post_likes for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can remove their own likes"
on public.post_likes for delete
to authenticated
using (auth.uid() = user_id);

create policy "Authenticated users can view prayers"
on public.prayer_requests for select
to authenticated
using (true);

create policy "Users can create prayer requests"
on public.prayer_requests for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can edit their own prayer requests"
on public.prayer_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own prayer requests"
on public.prayer_requests for delete
to authenticated
using (auth.uid() = user_id);

-- Automatically create a profile when a new authenticated user registers.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Believer'),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
